name: Deploy Vite to GitHub Pages

on:
  push:
    branches:
      - main # 監聽 main 分支的變更

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 設定 Node.js 環境
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 安裝依賴與建置
        run: |
          npm install
          npm run build
          touch dist/.nojekyll  # 避免 GitHub Pages 解析錯誤

      - name: 部署到 GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist # 指定輸出目錄

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 部署到 GitHub Pages
        uses: actions/deploy-pages@v2
